// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd9oJhkXzS4jCe8LrcDS8Lz4ecsDrLevQ',
    appId: '1:915164678715:web:a5aea33db0c66164892a1e',
    messagingSenderId: '915164678715',
    projectId: 'ostad-batch-7-4b7e8',
    authDomain: 'ostad-batch-7-4b7e8.firebaseapp.com',
    storageBucket: 'ostad-batch-7-4b7e8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg3dzAbc_JtLnf6s69s7wR7UEUwb5xo1E',
    appId: '1:915164678715:android:fd4ff44f4e9a37c8892a1e',
    messagingSenderId: '915164678715',
    projectId: 'ostad-batch-7-4b7e8',
    storageBucket: 'ostad-batch-7-4b7e8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhmfm26SbJVBtX3zX81KSWxAwkUC_SrOU',
    appId: '1:915164678715:ios:77caa490fbb36705892a1e',
    messagingSenderId: '915164678715',
    projectId: 'ostad-batch-7-4b7e8',
    storageBucket: 'ostad-batch-7-4b7e8.firebasestorage.app',
    iosBundleId: 'com.example.googleMapFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhmfm26SbJVBtX3zX81KSWxAwkUC_SrOU',
    appId: '1:915164678715:ios:4b8c86884764e4e3892a1e',
    messagingSenderId: '915164678715',
    projectId: 'ostad-batch-7-4b7e8',
    storageBucket: 'ostad-batch-7-4b7e8.firebasestorage.app',
    iosBundleId: 'com.example.sumApp',
  );

}