// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeUFtTPUdRdML_7_lsbrSs6nIQ9o3G708',
    appId: '1:817516250962:web:19d6f3229075ed130e9c8b',
    messagingSenderId: '817516250962',
    projectId: 'ostad-batch-07-bf028',
    authDomain: 'ostad-batch-07-bf028.firebaseapp.com',
    storageBucket: 'ostad-batch-07-bf028.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-yhelZZ4cl7GsyoYzV4-Un4dinKSJCiU',
    appId: '1:817516250962:android:848bf012ef80a9d00e9c8b',
    messagingSenderId: '817516250962',
    projectId: 'ostad-batch-07-bf028',
    storageBucket: 'ostad-batch-07-bf028.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWBy4h-jOInA8a3jvS3C2UR-CkThAAEJQ',
    appId: '1:817516250962:ios:f694e37aff2a49940e9c8b',
    messagingSenderId: '817516250962',
    projectId: 'ostad-batch-07-bf028',
    storageBucket: 'ostad-batch-07-bf028.firebasestorage.app',
    iosBundleId: 'com.example.sumApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWBy4h-jOInA8a3jvS3C2UR-CkThAAEJQ',
    appId: '1:817516250962:ios:f694e37aff2a49940e9c8b',
    messagingSenderId: '817516250962',
    projectId: 'ostad-batch-07-bf028',
    storageBucket: 'ostad-batch-07-bf028.firebasestorage.app',
    iosBundleId: 'com.example.sumApp',
  );
}
